#ifndef STATES_ID_H
#define STATES_ID_H

enum stateId
{
    CONNECT_STATE,
    INTRO_STATE,
    PLAY_STATE,
    OPTIONS_STATE,
    CONTROL_STATE,
    PADDLE_STATE,
    MUSIC_STATE,
    MULTICONTROL_STATE,
    DEMO_STATE,
    HOST_STATE,
    HOST_PLAY_STATE,
    CLIENT_PLAY_STATE
};
#endif // STATES_ID_H
