#ifndef STATES_ID_H
#define STATES_ID_H

enum stateId
{
    CONNECT_STATE,
    INTRO_STATE,
    PLAY_STATE,
    OPTIONS_STATE,
    CONTROL_STATE,
    PADDLE_STATE,
    MUSIC_STATE,
    MULTIPLAYER_CONTROL_STATE,
    DEMO_STATE,
    PADDLE_ONE_STATE,
    PADDLE_TWO_STATE
};
#endif // STATES_ID_H
